name: Daily Performance Check

on:
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  request-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install
      - name: Trigger SpeedVitals tests
        run: npm run request-tests
        env:
          SPEEDVITALS_API_KEY: ${{ secrets.SPEEDVITALS_API_KEY }}

  collect-and-build:
    needs: request-tests
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install
      - name: Fetch results and build report
        run: npm run fetch-and-build
        env:
          SPEEDVITALS_API_KEY: ${{ secrets.SPEEDVITALS_API_KEY }}
      - name: Commit data file and report
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/results.json public/index.html
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: update performance data and report"
            git push
          fi
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
